### ISSUE TITLE
[frontend][react] Render `Milestone.tsx` component

### ISSUE THREAD

**Issue by dyazdani** [dyazdani/trac#220]
- [ ] Has collapsable div that has all habit cards of habits that belong to milestone
- [ ] Has progress bar showing how many habit completions out of the total expected by due date
- [ ] Show text that says how many days left
