### ISSUE TITLE
[frontend][react] Add create Habit button to Milestone

### ISSUE THREAD

**Issue by dyazdani** [dyazdani/trac#276]
- [x] When Habit is created it is given the `milestoneId` of the Milestone on which the button was clicked
- [x] Eliminate the "Unassigned Habits" section of `Dashboard.tsx`
- [x] Ensure that Habits must be assigned to a Milestone
- [x] Remove FAB for creating Habit
- [x] Remove text on create Milestone FAB to it is circle
