### ISSUE TITLE
[frontend][react][chakra] Make last day of Milestone a Check-In Day for all Habits and display that in habit

### ISSUE THREAD

**Issue by dyazdani** [dyazdani/trac#506]
- [ ] Render "Final Check-In Day" on last routine day before Milestone dueDate
- [ ] Render "End" with an arrow below the checkbox on the Milestone dueDate 
- [ ] If due date is also the final Check-In Day, render the arrow below checkbox and say, "End & Final Due Date"
- [ ] Trigger "Send Status Report" button and styling as well as CTA Banner when it is the final routine day (regardless of whether it falls on a normal Check-In Day of the week).
